export const products = [
  {
    id: 1,
    name: "Organic Mango",
    description: "Fresh and juicy mangoes directly from Rajshahi farms.",
    price: 350,
    image: "https://i.ibb.co.com/8nXZqqwV/7g5j-ayby-210603.jpg",
    category: "Fruits",
  },
  {
    id: 2,
    name: "Premium Green Tea",
    description: "https://www.freepik.com/free-photo/glass-cup-dishware-healthy-food_1047576.htm#fromView=search&page=1&position=5&uuid=73ac4692-0c17-4834-a2b9-89a108eaccd7&query=green+tea",
    price: 500,
    image: "/images/green-tea.jpg",
    category: "Beverages",
  },
  {
    id: 3,
    name: "Handmade Clay Pot",
    description: "Traditional Bangladeshi clay pot for natural cooking.",
    price: 250,
    image: "/images/clay-pot.jpg",
    category: "Home & Kitchen",
  },
  {
    id: 4,
    name: "Natural Honey",
    description: "Pure, raw, and unprocessed honey from Sundarbans.",
    price: 700,
    image: "/images/honey.jpg",
    category: "Food",
  },
  {
    id: 5,
    name: "Bamboo Basket",
    description: "Eco-friendly handmade bamboo basket for storage.",
    price: 400,
    image: "/images/bamboo-basket.jpg",
    category: "Home Decor",
  },
  {
    id: 6,
    name: "Organic Brown Rice",
    description: "Chemical-free, healthy brown rice from local farms.",
    price: 800,
    image: "/images/brown-rice.jpg",
    category: "Food",
  },
  {
    id: 7,
    name: "Jute Bag",
    description: "Durable and eco-friendly jute shopping bag.",
    price: 150,
    image: "/images/jute-bag.jpg",
    category: "Accessories",
  },
  {
    id: 8,
    name: "Herbal Shampoo",
    description: "Made with natural herbs for strong and shiny hair.",
    price: 350,
    image: "/images/herbal-shampoo.jpg",
    category: "Personal Care",
  },
  {
    id: 9,
    name: "Earthen Water Pot",
    description: "Keeps water naturally cool and fresh.",
    price: 300,
    image: "/images/earthen-pot.jpg",
    category: "Home & Kitchen",
  },
  {
    id: 10,
    name: "Organic Turmeric Powder",
    description: "Pure turmeric powder with strong aroma and taste.",
    price: 200,
    image: "/images/turmeric.jpg",
    category: "Spices",
  },
];
